### ISSUE TITLE
Profile Picture Error

### ISSUE THREAD

**Issue by ghost** [marcovann/FirebaseChatDemo#1]
cant add profile picture ,it throws unfortunately app closed error :(

**Comment by aaadarshbisht** [comment]
how are you running this app? Please tell

**Comment by ghost** [comment]
its ok now :)

**Comment by aaadarshbisht** [comment]
can you tell me how are you logging in ,in the application?

**Comment by manikmittal1999** [comment]
Hey I am unable to see messages and users in app plz tell my why this is happening  but messages are storing in firebase database but not fetching in app
