### ISSUE TITLE
Enable Notifications for new messages

### ISSUE THREAD

**Issue by tgifriday** [marcovann/FirebaseChatDemo#4]
I see the code for notifications, but is there something need to enable notifications for new messages?

**Comment by marcovann** [comment]
Notifications are enabled using a node.js server (I didn't put the code on github yet).
I've just seen that Firebase add "Functions" feature that allows to run server code, I'll check if the current code is working on Firebase, then I'll push it on github.

**Comment by tgifriday** [comment]
Excellent, thank you.
I look forward to that update..  (BTW, I can do some testing if you like as well)

**Comment by tgifriday** [comment]
Node.js script n the works?

**Comment by marcovann** [comment]
I made a new repo https://github.com/marcovann/Firebase-Notification-Server

**Comment by tgifriday** [comment]
Thank you!

**Comment by manikmittal1999** [comment]
Hey I am unable to see messages and users in app plz tell my why this is happening  but messages are storing in firebase database but not fetching in app
