### ISSUE TITLE
Mesages and users are not showing

### ISSUE THREAD

**Issue by manikmittal1999** [marcovann/FirebaseChatDemo#7]
Hey nic project but when I imported on my android studio and make a apk of that users and mesaages are not showing after sending messages why? 
Incomplete project on github

**Comment by manikmittal1999** [comment]
Hey I am unable to see messages and users in app plz tell my why this is happening  but messages are storing in firebase database but not fetching in app

**Comment by marcovann** [comment]
It's solved now

**Comment by manikmittal1999** [comment]
No till not fix

**Comment by manikmittal1999** [comment]
Saving data on firebase but unable to see in app

**Comment by marcovann** [comment]
try now, the messages should be appearing
